import { useMemo } from 'react'
import { useWorkflowStore } from '@/stores/workflowStore'

/** Renders text with {{node_id}} replaced by colored label pills.
 *  Each unique node_id gets an evenly spaced hue so colors never overlap. */
export function TemplateText({ text }: { text: string }) {
  const nodes = useWorkflowStore((s) => s.nodes)

  // Collect unique node_ids in order of first appearance → assign evenly spaced hues.
  const hueMap = useMemo(() => {
    if (!text) return new Map<string, number>()
    const ids: string[] = []
    for (const m of text.matchAll(/\{\{(\w+)\}\}/g)) {
      if (!ids.includes(m[1])) ids.push(m[1])
    }
    const map = new Map<string, number>()
    ids.forEach((id, i) => map.set(id, (i * 360) / ids.length))
    return map
  }, [text])

  if (!text) return <span className="text-muted-foreground">Generated by AI</span>

  const parts = text.split(/(\{\{[^}]+\}\})/)
  return (
    <>
      {parts.map((part, i) => {
        const match = part.match(/^\{\{(\w+)\}\}$/)
        if (match) {
          const nodeId = match[1]
          const node = nodes.find((n) => n.id === nodeId)
          const label = node?.data.label ?? nodeId
          const hue = hueMap.get(nodeId) ?? 0
          return (
            <span
              key={i}
              className="inline-flex items-center px-1 py-0.5 mx-0.5 rounded font-medium dark:bg-[--pill-bg-dark] dark:text-[--pill-fg-dark]"
              style={{
                '--pill-bg-dark': `oklch(0.25 0.05 ${hue})`,
                '--pill-fg-dark': `oklch(0.8 0.12 ${hue})`,
                backgroundColor: `oklch(0.93 0.05 ${hue})`,
                color: `oklch(0.45 0.15 ${hue})`,
              } as React.CSSProperties}
            >
              {label}
            </span>
          )
        }
        return <span key={i}>{part}</span>
      })}
    </>
  )
}
