import { Label } from '@/components/ui/label'
import { Separator } from '@/components/ui/separator'
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select'
import { PromptEditor } from '@/components/editor/PromptEditor'
import { ModelSelector } from '@/components/editor/ModelSelector'
import type { NodeEditorFieldProps } from './NodeEditor'

export function OutputNodeEditor({ nodeId, config, setConfig }: NodeEditorFieldProps) {
  return (
    <>
      <Separator />
      <div className="space-y-1">
        <Label className="text-xs">Display Mode</Label>
        <Select
          value={(config.display_mode as string) ?? 'manual'}
          onValueChange={(v) => setConfig('display_mode', v)}
        >
          <SelectTrigger className="h-7 text-xs w-full" size="sm">
            <SelectValue />
          </SelectTrigger>
          <SelectContent>
            <SelectItem value="manual" className="text-xs">
              Manual layout
            </SelectItem>
            <SelectItem value="auto-layout" className="text-xs">
              Webpage with auto-layout
            </SelectItem>
          </SelectContent>
        </Select>
        <p className="text-[10px] text-muted-foreground">
          {(config.display_mode as string) === 'auto-layout'
            ? 'Layout automatically generated by AI'
            : 'Custom layout generated from your instructions'}
        </p>
      </div>

      {/* Manual layout: user-provided layout prompt + model selector */}
      {(config.display_mode as string) !== 'auto-layout' && (
        <>
          <div className="space-y-1">
            <Label className="text-xs">Layout Prompt</Label>
            <PromptEditor
              value={(config.layout_prompt as string) ?? ''}
              onChange={(v) => setConfig('layout_prompt', v)}
              nodeId={nodeId}
              placeholder="Describe your page layout, style, and component structure. Use {{ to reference upstream node outputs..."
            />
            <p className="text-[10px] text-muted-foreground">
              Describe layout, style, and components. Reference node outputs with {'{{node_id}}'}.
            </p>
          </div>
          <div className="space-y-1">
            <Label className="text-xs">Layout Model</Label>
            <ModelSelector
              value={(config.layout_model as string) ?? ''}
              onChange={(v) => setConfig('layout_model', v)}
              placeholder="Default model"
            />
          </div>
        </>
      )}

      {(config.display_mode as string) === 'auto-layout' && (
        <div className="space-y-1">
          <Label className="text-xs">Layout Model</Label>
          <ModelSelector
            value={(config.layout_model as string) ?? ''}
            onChange={(v) => setConfig('layout_model', v)}
            placeholder="Default model"
          />
        </div>
      )}
    </>
  )
}
