import { useState } from 'react'
import { Label } from '@/components/ui/label'
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select'
import { Collapsible, CollapsibleTrigger, CollapsibleContent } from '@/components/ui/collapsible'
import { ChevronRight } from 'lucide-react'
import { PromptEditor } from '@/components/editor/PromptEditor'
import { ModelSelector } from '@/components/editor/ModelSelector'
import { TemplateText } from '@/components/editor/TemplateText'
import type { OutputNodeConfig } from '@/lib/nodeConfigs'
import { fieldBoxExpand, type NodeEditorFieldProps } from './NodeEditor'

export function OutputNodeEditor({ nodeId, config, setConfig }: NodeEditorFieldProps<OutputNodeConfig>) {
  const [detailsOpen, setDetailsOpen] = useState(false)
  const isAutoLayout = config.display_mode === 'auto-layout'

  return (
    <div className="flex flex-col flex-1 min-h-0 gap-3">
      {/* Prompt — fixed height (PromptEditor has its own sizing) */}
      <div className="space-y-1 shrink-0">
        <Label className="text-xs">Prompt</Label>
        <PromptEditor
          value={config.prompt ?? ''}
          onChange={(v) => setConfig('prompt', v)}
          nodeId={nodeId}
          placeholder="Use {{ to reference upstream node results..."
        />
        <p className="text-[10px] text-muted-foreground">
          Specify which upstream results to collect. Leave empty to collect all.
        </p>
      </div>

      {/* Display Mode — fixed height */}
      <div className="space-y-1 shrink-0">
        <Label className="text-xs">Display Mode</Label>
        <Select
          value={config.display_mode ?? 'manual'}
          onValueChange={(v) => setConfig('display_mode', v)}
        >
          <SelectTrigger className="h-7 text-xs w-full" size="sm">
            <SelectValue />
          </SelectTrigger>
          <SelectContent>
            <SelectItem value="manual" className="text-xs">
              Manual layout
            </SelectItem>
            <SelectItem value="auto-layout" className="text-xs">
              Webpage with auto-layout
            </SelectItem>
          </SelectContent>
        </Select>
        <p className="text-[10px] text-muted-foreground">
          {isAutoLayout
            ? 'Layout automatically generated by AI'
            : 'Custom layout generated from your instructions'}
        </p>
      </div>

      {/* Layout Model — shared by both modes */}
      <div className="space-y-1 shrink-0">
        <Label className="text-xs">Layout Model</Label>
        <ModelSelector
          value={config.layout_model ?? ''}
          onChange={(v) => setConfig('layout_model', v)}
          placeholder="Default model"
        />
      </div>

      {/* Auto-layout: expandable read-only system prompt */}
      {isAutoLayout && (
        <Collapsible
          open={detailsOpen}
          onOpenChange={setDetailsOpen}
          className={detailsOpen ? 'flex-1 flex flex-col min-h-0 shrink-0' : 'shrink-0'}
        >
          <CollapsibleTrigger className="flex items-center gap-1 text-xs text-muted-foreground hover:text-foreground transition-colors py-1">
            <ChevronRight className={`h-3 w-3 transition-transform ${detailsOpen ? 'rotate-90' : ''}`} />
            System Prompt
          </CollapsibleTrigger>
          <CollapsibleContent className="flex-1 flex flex-col min-h-0 pt-1">
            <div className="flex-1 flex flex-col min-h-20 gap-1">
              <Label className="text-xs shrink-0">System Prompt</Label>
              <div className={fieldBoxExpand}>
                <TemplateText text={config.system_prompt ?? ''} />
              </div>
            </div>
          </CollapsibleContent>
        </Collapsible>
      )}
    </div>
  )
}
