package a2atypes

import "encoding/json"

// Part represents a piece of content in a message or artifact.
type Part struct {
	Type     string `json:"type"`               // "text", "file", "data"
	Text     string `json:"text,omitempty"`
	MimeType string `json:"mimeType,omitempty"`
	Data     any    `json:"data,omitempty"`
}

// TextPart creates a text part.
func TextPart(text string) Part {
	return Part{Type: "text", Text: text, MimeType: "text/plain"}
}

// DataPart creates a structured data part.
func DataPart(data any, mimeType string) Part {
	return Part{Type: "data", Data: data, MimeType: mimeType}
}

// Artifact is an output generated by an agent as a result of a task.
type Artifact struct {
	Name        string            `json:"name,omitempty"`
	Description string            `json:"description,omitempty"`
	Parts       []Part            `json:"parts"`
	Index       int               `json:"index"`
	Metadata    map[string]string `json:"metadata,omitempty"`
}

// FirstText returns the text content of the first text part, or "".
func (a Artifact) FirstText() string {
	for _, p := range a.Parts {
		if p.Type == "text" {
			return p.Text
		}
	}
	return ""
}

// FirstData returns the data of the first data part as JSON bytes, or nil.
func (a Artifact) FirstData() json.RawMessage {
	for _, p := range a.Parts {
		if p.Type == "data" {
			b, err := json.Marshal(p.Data)
			if err != nil {
				return nil
			}
			return b
		}
	}
	return nil
}

// TaskState represents the lifecycle state of an A2A task.
type TaskState string

const (
	TaskCreated       TaskState = "created"
	TaskWorking       TaskState = "working"
	TaskInputRequired TaskState = "input-required"
	TaskCompleted     TaskState = "completed"
	TaskFailed        TaskState = "failed"
	TaskCanceled      TaskState = "canceled"
)

// Task is the fundamental unit of work in A2A.
type Task struct {
	ID        string     `json:"id"`
	ContextID string     `json:"contextId,omitempty"`
	Status    TaskState  `json:"status"`
	Messages  []Message  `json:"messages,omitempty"`
	Artifacts []Artifact `json:"artifacts,omitempty"`
}

// Message is a communication turn between client and agent.
type Message struct {
	Role  string `json:"role"` // "user" or "agent"
	Parts []Part `json:"parts"`
}

// NewTask creates a new task with a unique ID and "created" status.
func NewTask(contextID string) *Task {
	return &Task{
		ID:        GenerateID("task"),
		ContextID: contextID,
		Status:    TaskCreated,
	}
}

// AgentCard describes an A2A agent's identity and capabilities.
type AgentCard struct {
	Name               string       `json:"name"`
	Description        string       `json:"description"`
	URL                string       `json:"url"`
	Capabilities       Capabilities `json:"capabilities"`
	Skills             []Skill      `json:"skills"`
	DefaultInputModes  []string     `json:"defaultInputModes"`
	DefaultOutputModes []string     `json:"defaultOutputModes"`
}

// Capabilities describes what the agent supports.
type Capabilities struct {
	Streaming         bool `json:"streaming"`
	PushNotifications bool `json:"pushNotifications"`
}

// Skill describes a specific capability of the agent.
type Skill struct {
	ID          string   `json:"id"`
	Name        string   `json:"name"`
	Description string   `json:"description"`
	InputModes  []string `json:"inputModes"`
	OutputModes []string `json:"outputModes"`
}
