import { useWorkflowStore } from '@/entities/workflow'
import { getAllNodeDefinitions } from '@/entities/node'

const pillColors: Record<string, string> = Object.fromEntries(
  getAllNodeDefinitions().map((def) => [def.type, `bg-node-${def.type}/15 text-node-${def.type}`]),
)

/** Renders text with {{node_id}} replaced by colored label pills.
 *  Pill colors match the source node's type color. */
export function TemplateText({ text }: { text: string }) {
  const nodes = useWorkflowStore((s) => s.nodes)

  if (!text) return <span className="text-muted-foreground">Generated by AI</span>

  const parts = text.split(/(\{\{[^}]+\}\})/)
  return (
    <>
      {parts.map((part, i) => {
        const match = part.match(/^\{\{(\w+)\}\}$/)
        if (match) {
          const nodeId = match[1]
          const node = nodes.find((n) => n.id === nodeId)
          const label = node?.data.label ?? nodeId
          const nodeType = (node?.data.nodeType ?? 'agent') as string
          const colors = pillColors[nodeType] ?? 'bg-muted text-muted-foreground'
          return (
            <span
              key={i}
              className={`inline-flex items-center px-1 py-0.5 mx-0.5 rounded font-medium ${colors}`}
            >
              {label}
            </span>
          )
        }
        return <span key={i}>{part}</span>
      })}
    </>
  )
}
